---
title: "Resume"
author: ''
showpagemeta: false
slug: new-post
categories: []
tags: []
description: ''
---

**EDUCATION**
 
***The University of Texas at Austin*** • May 2020

• B.S.A. Biology, *College of Natural Sciences*

• B.A. Health and Society (Concentration: Health and the Economy), *College of Liberal Arts*

• Business of Healthcare Certificate, *McCombs School of Business*

**EXPERIENCE**

***Osier Laboratory, Dell Medical School*** • May 2018-Present • *Research Assistant*

•	Research barriers that prevent children from being admitted into emergency departments in order to devise ways that deconstruct parents’ hesitancies towards hospitals

•	Encourage pediatric patients and their parents to participate in a head injury study that investigates how to improve quality of life for people diagnosed with traumatic brain injuries

•	Prepare meeting agendas and execute meetings for over 100+ undergraduate research assistants

•	Collaborate with fellow research assistants to publish research papers for scientific journals

***Osier Laboratory, Dell Medical School*** • January 2019-July 2019 • *Accountability Officer*

•	Established an officer position that oversees 100+ research assistants’ involvement in the lab

• Streamlined a monitoring system that records research assistants’ hours weekly

• Communicated with research assistants that did not meet their weekly requirements

•	Improved consistency of research assistants’ involvements in the lab

***People’s Community Clinic, Austin, Texas*** • January 2019-July 2019 • *Community-Centered Health Homes Intern*

•	Provided patients the opportunity to address their health issues by coordinating in-house meetings in low-income neighborhoods in efforts to decrease barriers in the community that may impact health

•	Developed billingual resources which provided families information on how to receive financial, home, andfamily assistance around the Austin area

•	Wrote monthly blog posts about the social determinants of health and its presence in Austin

***CVS Health, Austin, Texas*** • May 2018-April 2019 • *Certified Pharmacy Technician (CPhT)*

•	Demonstrated effective multi-tasking skills by maintaining the organization of filling prescriptions while managing data in a computer system in a fast-paced, high pressure environment

•	Mitigated questions and concerns of customers by providing assistance towards resolutions

•	Executed friendly and compassionate interactions in efforts to retain customers and increase customer satisfaction

**COMMUNITY INVOLVEMENT**

***Down Syndrome Association of Central Texas, Austin, Texas*** •	July 2018-January 2020 • *Recreational Activities Coordinator*

•	Create and conduct engaging dance, fitness, and outdoor events for families and their children who have Down syndrome

•	Promote a healthy lifestyle for children who have Down Syndrome through education and mentorship

***Dell Children’s Medical Center, Austin, Texas*** • January 2017-January 2018 • *College Program Volunteer*

•	Improved families’ hospital stay through organizing creative and playful activities for patients and siblings

•	Advocated patients’ needs to their healthcare providers while assisting them in the absence of a guardian

**AFFILIATIONS**

***Longhorn Awakening, UT Austin***– Staffer/Music Staff Head	August 2017-Present

***Texas Business of Healthcare Association, UT Austin***– Member	August 2017-August 2018

**SKILLS**
 

**Computer**: Microsoft Office, RStudio

**Language**: Conversational Spanish
